### ISSUE TITLE
Getting this error right after entering login info

### ISSUE THREAD

**Issue by dantdanielson** [AnmolMajithia/RAM-Reddit-Account-Mover#2]
`Authenticating...Traceback (most recent call last):
  File "C:/Users/chint/Downloads/RAM-Reddit-Account-Mover-main/RAM-Reddit-Account-Mover-main/main.py", line 9, in <module>
    login_details = logincaller()
  File "C:\Users\chint\Downloads\RAM-Reddit-Account-Mover-main\RAM-Reddit-Account-Mover-main\utils\copy_subscription.py", line 44, in logincaller
    auth = requests.auth.HTTPBasicAuth(CLIENT_ID, SECRET_KEY)
NameError: name 'requests' is not defined`

**Comment by AnmolMajithia** [comment]
Hey @dantdanielson, sorry I forgot about this repo and just checked it today, I have pushed a hotfix which should solve the above error, please redownload/pull again and retry and let me know if something else blocks you. Thanks!
